### ISSUE TITLE
OpenSSL verification error

### ISSUE THREAD

**Issue by haberbyte** [tenderlove/gem_survey#4]
While trying to report the data using the script i get:

```
$ curl https://raw.githubusercontent.com/tenderlove/gem_survey/master/survey.rb | ruby
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2932  100  2932    0     0  20644      0 --:--:-- --:--:-- --:--:-- 20794
/Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
    from /Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
    from /Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
    from /Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:923:in `connect'
    from /Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
    from /Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:852:in `start'
    from /Users/janhab/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1375:in `request'
    from -:120:in `<main>'
```

Operating system: OSX Yosemite

I use RVM at work, rbenv at home.
On both systems i get the same error.

---

It is an issue with outdated certificates somehow i'm afraid.
Possible solutions are found here: http://railsapps.github.io/openssl-certificate-verify-failed.html

I just wanted to report this issue because maybe I'm not the only one encountering this issue.
And maybe many people try it out and give up => Useful survey data lost :-(

**Comment by haberbyte** [comment]
I tried multiple ruby versions and it seems to also occur with 2.2.2.

```
/Users/janhab/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
```

**Comment by haberbyte** [comment]
This gist has the solution that worked for me:

https://gist.github.com/mislav/5026283

**Comment by hayesr** [comment]
I'm using rbenv and Ruby 2.2.2p95. The first thing I tried was `brew upgrade openssl` and that seemed to have solved it for me.

I don't think the magic is just a new version, the upgrade does this:

```
A CA file has been bootstrapped using certificates from the system
keychain. 
```

I think it brought in the system certs, made them available to Ruby and triggered something to awaken the mystical SSL Cert Faeries.

**Comment by nijikon** [comment]
@hayesr Thanks! `brew reinstall openssl` fixed the issue.
